name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to SiteGround
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SITEGROUND_HOST }}
          username: ${{ secrets.SITEGROUND_USER }}
          key: ${{ secrets.SITEGROUND_SSH_KEY }}
          port: 18765
          script: |
            cd ~/public_html/wp-content/themes

            # If the folder doesn't exist, clone it
            if [ ! -d "dev/.git" ]; then
              git clone git@github.com:capstone-1252/bee-inc.git dev
            else
              cd dev
              git pull origin main
            fi
